In [1]:
import os
import sys
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from scipy.io import loadmat

In [3]:
!pip install pyod

  Created wheel for pyod: filename=pyod-0.8.1-cp37-none-any.whl size=105657 sha256=7de515dc5675f072837a1c32138b9ef70d6965876c95bb3636737bf730701c55
  Stored in directory: C:\Users\HP\AppData\Local\pip\Cache\wheels\2e\ca\18\727e9d98a41f5f4385a97d5b429f3a9c8fbee13f9780c18642
  Created wheel for combo: filename=combo-0.1.1-cp37-none-any.whl size=42121 sha256=75481e2fc225c4b8ddbf6275439dfb899f5f98b48cc18d4e268e22f855d8c26b
  Stored in directory: C:\Users\HP\AppData\Local\pip\Cache\wheels\55\ec\e5\a2331372c676c467e70c6646e646edf6997d5c4905b8c0f5e6
  Created wheel for suod: filename=suod-0.0.4-cp37-none-any.whl size=2167164 sha256=cb0ead0f6e8e9e9e3218eef7e9628027ccf6a5da3f4cb92d74f1b9ad2a3ec468
  Stored in directory: C:\Users\HP\AppData\Local\pip\Cache\wheels\57\55\e5\a4fca65bba231f6d0115059b589148774b41faea25b3f2aa27
Successfully built pyod combo suod


In [5]:
from pyod.models.pca import PCA
from pyod.models.mcd import MCD
from pyod.models.ocsvm import OCSVM
from pyod.models.lof import LOF
from pyod.models.cblof import CBLOF
from pyod.models.knn import KNN
from pyod.models.hbos import HBOS
from pyod.models.abod import ABOD
from pyod.models.iforest import IForest


E:\AKSHAY\python\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


ImportError: cannot import name 'FeatureBagiing' from 'pyod.models.feature_bagging' (E:\AKSHAY\python\lib\site-packages\pyod\models\feature_bagging.py)

In [6]:
from pyod.models.feature_bagging import FeatureBagging

In [8]:
from pyod.utils.utility import standardizer
from pyod.utils.utility import precision_n_scores
from sklearn.metrics import roc_auc_score

In [14]:
mat_file_list = ['arrhythmia.mat',
                'cardio.mat',
                'glass.mat',
                "ionosphere.mat",
                "letter.mat",
                "lympho.mat",
                "mnist.mat",
                "musk.mat", 
                "optdigits.mat",
                "pendigits.mat",
                "pima.mat",
                "satellite.mat",
                "satimage-2.mat",
                "shuttle.mat",
                "vertebral.mat",
                "vowels.mat",
                "wbc.mat"]

In [19]:
#loading the MAT file.

data=loadmat("C:/Users/HP/LetsUpgrade/Project -1/cardio.mat")
data

{'__header__': b'MATLAB 5.0 MAT-file, written by Octave 3.8.0, 2014-12-18 10:48:09 UTC',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[ 0.00491231,  0.69319077, -0.20364049, ...,  0.23149795,
         -0.28978574, -0.49329397],
        [ 0.11072935, -0.07990259, -0.20364049, ...,  0.09356344,
         -0.25638541, -0.49329397],
        [ 0.21654639, -0.27244466, -0.20364049, ...,  0.02459619,
         -0.25638541,  1.14001753],
        ...,
        [-0.41835583, -0.91998844, -0.16463485, ..., -1.49268341,
          0.24461959, -0.49329397],
        [-0.41835583, -0.91998844, -0.15093411, ..., -1.42371616,
          0.14441859, -0.49329397],
        [-0.41835583, -0.91998844, -0.20364049, ..., -1.28578165,
          3.58465295, -0.49329397]]),
 'y': array([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [1.],
        [1.]])}

In [20]:
#reshaping :

type(data['X']),data['X'].shape

(numpy.ndarray, (1831, 21))

In [23]:
# reshaping for DV
type(data['y']), data['y'].shape

(numpy.ndarray, (1831, 1))

In [26]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
!pip install time

  ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time


In [28]:
#exploring files

from time import time
random_state = np.random.RandomState(42)

In [36]:
for mat_file in mat_file_list:
    print("\n.. Processing", mat_file, '...')
    mat=loadmat("C:/Users/HP/LetsUpgrade/Project -1/arrhythmia.mat")
    mat


.. Processing arrhythmia.mat ...

.. Processing cardio.mat ...

.. Processing glass.mat ...

.. Processing ionosphere.mat ...

.. Processing letter.mat ...

.. Processing lympho.mat ...

.. Processing mnist.mat ...

.. Processing musk.mat ...

.. Processing optdigits.mat ...

.. Processing pendigits.mat ...

.. Processing pima.mat ...

.. Processing satellite.mat ...

.. Processing satimage-2.mat ...

.. Processing shuttle.mat ...

.. Processing vertebral.mat ...

.. Processing vowels.mat ...

.. Processing wbc.mat ...


In [39]:
X = mat['X']
y = mat['y'].ravel()
outliners_fraction = np.count_nonzero(y) / len(y)
outliers_percentage = round(outliners_fraction*100, ndigits=4)

In [40]:
outliners_fraction

0.14601769911504425

In [42]:
#construct containers for saving results

roc_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
prn_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
time_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]

In [43]:
print(roc_list)
print(prn_list)
print(time_list)

['wbc', 452, 274, 14.6018]
['wbc', 452, 274, 14.6018]
['wbc', 452, 274, 14.6018]


In [44]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4,
                                                    random_state=random_state)


In [45]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 59.    1.  155.  ...  -1.2  14.    0.4]
 [ 26.    0.  180.  ...  -1.   16.8   7.4]
 [ 68.    0.  164.  ...   2.7  18.8  41.4]
 ...
 [ 34.    1.  165.  ...   0.8   1.9   8.1]
 [ 39.    1.  164.  ...   1.3  24.1  33.7]
 [ 19.    1.  157.  ...   1.3   9.4  17.9]]
[[ 51.    0.  170.  ...   2.6  23.7  47.6]
 [ 45.    0.  175.  ...   1.   10.5  17.9]
 [ 31.    1.  165.  ...   0.9   9.6  14.4]
 ...
 [ 56.    0.  170.  ...   1.   24.   32.2]
 [ 50.    0.  172.  ...   1.6  14.2  27.6]
 [ 51.    1.  160.  ...   1.5  12.   24. ]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 0 0 1 0 0 0 1 1

In [46]:
#standardizing data for processing:
X_train_norm, X_test_norm = standardizer(X_train, X_test)
print(X_train_norm)
print(X_test_norm)

[[ 0.79514353  0.9321832  -0.36920653 ... -1.61666889 -0.41511185
  -1.60714874]
 [-1.25412696 -1.07275051  0.50113941 ... -1.48155177 -0.21381656
  -1.22257319]
 [ 1.35403549 -1.07275051 -0.05588199 ...  1.018115   -0.07003421
   0.64536522]
 ...
 [-0.75733411  0.9321832  -0.02106815 ... -0.26549767 -1.28499508
  -1.18411563]
 [-0.44683858  0.9321832  -0.05588199 ...  0.07229514  0.31098902
   0.22233211]
 [-1.6888207   0.9321832  -0.29957885 ...  0.07229514 -0.74581126
  -0.64570986]]
[[ 0.29835069 -1.07275051  0.15300104 ...  0.95055643  0.28223255
   0.98598928]
 [-0.07424395 -1.07275051  0.32707022 ... -0.13038054 -0.66673097
  -0.64570986]
 [-0.94363143  0.9321832  -0.02106815 ... -0.19793911 -0.73143302
  -0.83799763]
 ...
 [ 0.60884622 -1.07275051  0.15300104 ... -0.13038054  0.30379991
   0.13992306]
 [ 0.23625158 -1.07275051  0.22262871 ...  0.27497082 -0.40073362
  -0.11279802]
 [ 0.29835069  0.9321832  -0.19513734 ...  0.20741226 -0.5588942
  -0.31057973]]


In [50]:
classifiers = {"Angel-based Outlier Detector (ABOD)" : ABOD(
               contamination = outliers_fraction, check_estimator = False, 
                random_state = random_state),
              'Feature Bagging' : FeatureBagging(contamination = outliers_fraction,
                                                random_state=random_state),
              "Histogram-base Outlier Detection (HBOS)": HBOS(
                   contamination = outliers_fraction),
              "Isolation Forest": IForest(contamination= outliers_fraction,
                                         random_state= random_state),
              "K Nearest Neighbors (KNN)" : KNN(contamination = outliers_fraction),
              'Local Outlier Factor (LOF)' : LOF(
                contamination= outliers_fraction),
              "Minimum Covariance Determinat (MCD)": MCD(
                contamination=outliers_fraction, random_state=random_state),
              }
for clf_name, clf in classifiers.items():
    t0 = time()
    clf.fit(X_train_norm)
    test_scores= clf.decision_function(X_test_norm)
    t1 = time()
    duration = round(t1 - t0, ndigits =4)
    time_list.append(duration)
    
    roc = round(roc_auc_score(y_test, test_scores), ndigits =4)
    prn = round(precision_n_scores(y_test, test_scores), ndigits=4)
    
    print('{clf_name} ROC: (roc), precision @ rank n: {prn},'
         'execution time: {duration}s'.format(
         clf_name = clf_name, roc=roc, prn = prn), duration = duration))
    
        roc_list.appead(roc)
        prn_list.append(prn)
    
    temp_df = pd.DataFrame (time_list).transpose()
    temp_df.columns = df_columns
    time_df =pd.concat([roc_df, temp_df], axis=0)
    
    temp_df = pd.DataFrame (prn_list).transpose()
    temp_df.columns = df_columns
    time_df =pd.concat([prn_df, temp_df], axis=0)
    
    

SyntaxError: invalid syntax (<ipython-input-50-df3184157604>, line 29)