2D array creation

In [13]:
import numpy as np
a1= np.array([[1,2,3], [4,5,6],[7,8,9]])
print("print the array name :\n",  a1)
print("shape of array = ", (a1.shape))
a2= len(a1)
print("len of a1 =", a2)

print the array name :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of array =  (3, 3)
len of a1 = 3


In [15]:
a1[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a1[3:] #slicing , alrd left to write is happen

array([], shape=(0, 3), dtype=int32)

In [23]:
print(a1[1][-2])
a1.shape


5


(3, 3)

#functions

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a0=np.full((2,3), 45)
a0

array([[45, 45, 45],
       [45, 45, 45]])

In [28]:
a2=np.ones_like(a1)
a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
a= np.array([[1,2,3], [4,5,6],[7,8,9], [10,11,12]])
print("Prniting array(a) : \n" ,a)
print("printing slice of 1:\n ", a[:1])
print("Printing slice in -1: \n", a[:-1])

Prniting array(a) : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
printing slice of 1:
  [[1 2 3]]
Printing slice in -1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
b= a[1:3, :2]
print("Printing a:\n", a)
print("Printing b: \n" , b)


Printing a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Printing b: 
 [[4 5]
 [7 8]]


In [45]:
b[0][0]=500
print(b)


[[500   5]
 [  7   8]]


In [46]:
a

array([[  1,   2,   3],
       [500,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [53]:
print("Print a: \n", a)
r1= a[1,:]
r2= a[1:2, :]
r3= a[[1], :]
print("print r1: \n",r1, r1.shape)
print("print r2: \n",r2, r2.shape)
print("print r3: \n",r3, r3.shape)

Print a: 
 [[  1   2   3]
 [500   5   6]
 [  7   8   9]
 [ 10  11  12]]
print r1: 
 [500   5   6] (3,)
print r2: 
 [[500   5   6]] (1, 3)
print r3: 
 [[500   5   6]] (1, 3)
