# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
#introducing new varibale
axs = np.random.random(3) # 3x1 array
axs

array([0.74590883, 0.67352649, 0.74041606])

In [2]:
axs = np.random.random((3,3,3)) #3x3 array is used.
axs

array([[[0.51620427, 0.20221797, 0.48849233],
        [0.18672818, 0.80848263, 0.36102601],
        [0.38181588, 0.0214566 , 0.23039032]],

       [[0.73901447, 0.05316824, 0.88093577],
        [0.14413619, 0.56407281, 0.64492791],
        [0.5607791 , 0.63982515, 0.125154  ]],

       [[0.7921362 , 0.78372728, 0.66384871],
        [0.00846756, 0.98541674, 0.45039661],
        [0.06579816, 0.74855458, 0.75603938]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
#first will creat array, of 5x5:
axs= np.random.random((1,2,3,4,5))
axs

array([[[[[0.59092361, 0.82126351, 0.27922178, 0.30634566, 0.95977422],
          [0.24093274, 0.96937338, 0.86934242, 0.64988278, 0.46650676],
          [0.60604586, 0.8270585 , 0.09923959, 0.8257367 , 0.68212383],
          [0.4568567 , 0.27618636, 0.97677129, 0.85832342, 0.77057634]],

         [[0.67758851, 0.79262442, 0.59009507, 0.60764103, 0.77825274],
          [0.9120008 , 0.86596064, 0.4992585 , 0.88176264, 0.0077015 ],
          [0.8134523 , 0.45789471, 0.07772325, 0.51835216, 0.01836187],
          [0.33679941, 0.36275522, 0.67586532, 0.79173205, 0.70322909]],

         [[0.32266253, 0.32381583, 0.44155011, 0.68619768, 0.35849849],
          [0.98166492, 0.23120411, 0.04254949, 0.17913004, 0.40212308],
          [0.54424842, 0.01193366, 0.38716236, 0.26497675, 0.11686374],
          [0.0935296 , 0.61074097, 0.22114333, 0.43029082, 0.75232921]]],


        [[[0.770908  , 0.06868061, 0.85326698, 0.36324977, 0.90737359],
          [0.09415034, 0.96195667, 0.6669432 , 0.2296889

In [4]:
#now will creat 5x5 random matric , active on main diagonal only
aks0 = (1,2,4,5)
aks= np.diag((aks0))
aks

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:

x = np.ones((8,8))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int) #performing row wise.
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

The term “normalization” refers to the scaling down of the data set such that the normalized data falls in the range between 0 and 1. Such normalization techniques help in comparing corresponding normalized values from two or more different data sets in a way that it eliminates the effects of the variation in the scale of the data sets i.e. a data set with large values can be easily compared with a data set of smaller values.

#ONly magnitueds changes, ot direction:
Any vector, when normalized, only changes its magnitude, not its direction. Also, every vector pointing in the same direction, gets normalized to the same vector (since magnitude and direction uniquely define a vector). Hence, unit vectors are extremely useful for providing directions.

In [6]:
#making a matrix
x=np.random.random((5,5))
print(x)


[[0.71384262 0.43731197 0.01476699 0.66156979 0.40829659]
 [0.68721732 0.17795219 0.69167188 0.75734987 0.13726389]
 [0.19863764 0.69248104 0.98654127 0.91162284 0.87192784]
 [0.01017144 0.83871307 0.73607272 0.32040621 0.19600881]
 [0.85107741 0.2784346  0.29050155 0.7939252  0.0396422 ]]


In [7]:
#we nee more terms, for peroper normalization 
# FINDING max & min and range, : xmax, xmin = x.max(), x.min()
#x = (x - xmin)/(xmax - xmin)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

After normalization:
[[0.72070148 0.43747821 0.00470677 0.66716354 0.40776061]
 [0.69343179 0.17184139 0.69799416 0.76526169 0.13016836]
 [0.19302747 0.6988229  1.         0.92326839 0.88261269]
 [0.         0.84859406 0.7434696  0.3177431  0.19033503]
 [0.86125763 0.27475569 0.28711468 0.80272223 0.03018402]]


In [8]:

x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.55590344 0.31984161 0.94290213]
 [0.26465522 0.48768786 0.88544971]
 [0.26116153 0.90795048 0.54875686]]
After normalization:
[[0.43233733 0.08607392 1.        ]
 [0.00512467 0.33227643 0.91572686]
 [0.         0.94873175 0.42185449]]


# 5.  How to find common values between two arrays?

In [9]:
# making two arrays, of different length, and try t o find the same

In [10]:
#introducing arr1 , arr2
arr1 = np.array([-1, 49, 320, 8, 12]) #introducing arry
print("Array1: ",arr1)
arr2 = [12, 30, -1] #introducing second array
print("Array2: ",arr2)
print("Common values between two arrays:")
print(np.intersect1d(arr1, arr2))

Array1:  [ -1  49 320   8  12]
Array2:  [12, 30, -1]
Common values between two arrays:
[-1 12]


# 6.How to get the dates of yesterday, today and tomorrow?

introducing variales, for all dates

In [11]:
#yst =yesterday, Tdy: today, Ftr: future
Tdy = np.datetime64('today', 'D')
yst = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Today: ", Tdy)
print("Yestraday: ",yst)


Today:  2020-08-03
Yestraday:  2020-08-02


In [12]:
#similar with tommarow: tmr
tmr  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tmr)

Tomorrow:  2020-08-04


# 7. Consider two random array A and B, check if they are equal

In [13]:
# x= variables , 
x = np.random.randint(1,5,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Checking above two arrays are equal or not!") #return will be boolean.
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[3 3 3 3 3 3]
Second array:
[1 0 1 0 1 0]
Checking above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
#making random array, for vector size10

a= np.array([2,54,7,4,-18,0,100,23,1,9])
print(a)
# Get the maximum element from a Numpy array
maxElement = np.amax(a)
minElement = np.amin(a)
print('Max element from Numpy Array : ', maxElement)
print('Min element from Numpy Array :', minElement)
a[a.argmax()] = -1
print("Maximum value replaced by -1:")
print(a)
a[a.argmin()] = 5000
print("Min value replaced by 5000:")
print(a)

[  2  54   7   4 -18   0 100  23   1   9]
Max element from Numpy Array :  100
Min element from Numpy Array : -18
Maximum value replaced by -1:
[  2  54   7   4 -18   0  -1  23   1   9]
Min value replaced by 5000:
[   2   54    7    4 5000    0   -1   23    1    9]


# 9. How to print all the values of an array? 

In [15]:
import numpy as np
np.arange(100).reshape(25,4).tolist()

[[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27],
 [28, 29, 30, 31],
 [32, 33, 34, 35],
 [36, 37, 38, 39],
 [40, 41, 42, 43],
 [44, 45, 46, 47],
 [48, 49, 50, 51],
 [52, 53, 54, 55],
 [56, 57, 58, 59],
 [60, 61, 62, 63],
 [64, 65, 66, 67],
 [68, 69, 70, 71],
 [72, 73, 74, 75],
 [76, 77, 78, 79],
 [80, 81, 82, 83],
 [84, 85, 86, 87],
 [88, 89, 90, 91],
 [92, 93, 94, 95],
 [96, 97, 98, 99]]

# 10.Subtract the mean of each row of a matrix

In [16]:

print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.81263339 0.16900989 0.66853366 0.05033383 0.03434857 0.89674358
  0.93386086 0.86286925 0.29579359 0.79235713]
 [0.22862252 0.65745408 0.41501514 0.77710157 0.72381843 0.45797111
  0.70453433 0.75004543 0.86292717 0.61765647]
 [0.0466524  0.67491208 0.62616038 0.43141467 0.95248646 0.59214658
  0.93605678 0.02617347 0.75372585 0.75081628]
 [0.91130058 0.15569806 0.90253887 0.84748909 0.44794227 0.65297345
  0.36387127 0.79444272 0.24473426 0.37997127]
 [0.65806267 0.82861164 0.67058747 0.92301564 0.12377448 0.42423038
  0.49817851 0.3884579  0.75668719 0.69790656]]

Subtract the mean of each row of the said matrix:

[[ 0.26098502 -0.38263848  0.11688529 -0.50131454 -0.51729981  0.34509521
   0.38221248  0.31122087 -0.25585479  0.24070876]
 [-0.3908921   0.03793946 -0.20449949  0.15758694  0.10430381 -0.16154352
   0.0850197   0.13053081  0.24341255 -0.00185816]
 [-0.5324021   0.09585759  0.04710589 -0.14763983  0.37343197  0.01309208
   0.35700229 -0.55288103  0.1

In [17]:

print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=-1, keepdims=True)
print(Y)

Original matrix:

[[0.09857395 0.17928798 0.46657428 0.25745957 0.87208977 0.95684081
  0.73927469 0.82667201 0.6625079  0.64315205]
 [0.60015534 0.68165198 0.89793778 0.89371338 0.77407767 0.79747298
  0.71555817 0.4121481  0.87307265 0.42557588]
 [0.22959039 0.42941276 0.67652392 0.5316303  0.03572011 0.04354176
  0.38521841 0.01957475 0.50943998 0.87359098]
 [0.53860106 0.10987234 0.21709803 0.64905373 0.27832109 0.2514905
  0.93575139 0.58421343 0.13019312 0.31777481]
 [0.92230766 0.34357875 0.97781363 0.98350985 0.73299087 0.22558667
  0.71427888 0.92881498 0.28400979 0.89421509]]

Subtract the mean of each row of the said matrix:

[[-0.47166935 -0.39095532 -0.10366902 -0.31278373  0.30184647  0.38659751
   0.16903139  0.25642871  0.0922646   0.07290875]
 [-0.10698106 -0.02548441  0.19080139  0.18657699  0.06694128  0.09033659
   0.00842178 -0.2949883   0.16593625 -0.28156051]
 [-0.14383395  0.05598843  0.30309959  0.15820597 -0.33770423 -0.32988258
   0.01179408 -0.35384958  0.13

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
import numpy as np
arr1= np.ones(5)
arr2= np.random.randint(0, len(arr1), 10)
arr1+=np.bincount(arr2,minlength=len(arr1))
arr1

array([3., 4., 2., 4., 2.])

# 12.How to get the diagonal of a dot product?

In [23]:
a=np.array([2,4,9])
b= np.array([2,0,8])
print(a)
print(b)
print(np.dot(a,b))

[2 4 9]
[2 0 8]
76


# 13.How to find the most frequent value in an array?

In [20]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[4 0 3 4 7 5 9 0 2 6 6 3 2 7 2 5 6 7 5 2 8 6 7 0 8 3 3 7 0 2 4 0 0 0 8 3 8
 3 4 2]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [21]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [22]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
